# Lambda function (람다 함수)

<img src = https://runestone.academy/ns/books/published/fopp/_images/lambda.gif width = 400>

- 문법 
  - (기본 형태) lambda argument: expression 
  - (예시) lambda x: x + 2

- 파이썬의 람다 함수 기능은 수학 이론 '람다 대수 (lambda calculus)'에서 유래 
  - 인풋과 아웃풋의 관계 즉 함수(函數)를 f(x) = x + 2와 같은 형태로 표현하자
  - 람다 함수 기능은 파이썬 뿐 아니라 형태는 다르나 다양한 프로그래밍 언어에서도 활용중
- 람다 함수의 장점
  - 간결한 코드 작성 
  - 메모리 절약에 따른 빠른 실행



- 참고 링크
  - [[Python-기초] 람다(lambda)식](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=rekt77&logNo=221426577361)
  - [람다 표현식과 맵, 필터, 리듀스](https://soooprmx.com/%EB%9E%8C%EB%8B%A4%ED%91%9C%ED%98%84%EC%8B%9D%EA%B3%BC-%EB%A7%B5-%ED%95%84%ED%84%B0-%EB%A6%AC%EB%93%80%EC%8A%A4-python/)
  - [점프 투 파이썬 - 04-1 함수 (가장 마지막 문단)](https://wikidocs.net/24)

In [1]:
#일반 함수
def func_name(x):
    return x+2

#람다 함수
lambda x: x+2

### argument가 없는 경우

In [2]:
lambda : print('Hello World')

In [3]:
hello = lambda : print('Hello World')

In [4]:
hello()

Hello World

### argument가 있는 경우 (1) - 변수 저장 후 활용하기

In [5]:
둘더하기 = lambda x: x + 2

In [6]:
둘더하기(6)

8

In [7]:
#일반 파이썬 함수

def 둘더하기_일반(x):
    return x + 2

In [8]:
둘더하기_일반(6)

8

### argument가 있는 경우 (2) - 변수 저장 없이 활용하기

In [9]:
# 괄호를 치면 바로 lambda함수 실행 가능

(lambda x: x + 2)(6)

8

#복수 파라미터 사용

In [10]:
member = lambda x, y: x + y + 4 
member(100,100)

204

In [11]:
(lambda x, y: x + y + 4)(100,100)

204

## 다른 파이썬 함수들과의 활용 예시

### 리스트 - filter()와 map()

In [13]:
#filter()
#filter(함수, 시퀀스 데이터)
#시퀀스 데이터 중 주어진 함수에 따른 값만 필터링

price = [100, 200, 300, 400, 500, 600]

filter(lambda x: x % 3 == 0, price)

#결과 확인(filter 오브젝트)

In [14]:
#리스트로 다시 만들어줘야 결과 출력

list(filter(lambda x: x % 3 == 0, price))

[300, 600]

In [15]:
#혹은 list comprehend로도 필터링 가능

[x for x in price if x % 3 == 0]

[300, 600]

In [16]:
#map()
#map(함수, 시퀀스 데이터)

price2 = [10, 20, 30, 40, 50, 60]
list(map(lambda x: x + x, price2))

[20, 40, 60, 80, 100, 120]

### 데이터 프레임

In [18]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    '상품': ['특산품A','특산품B','특산품C'],
    '지역': ['안산', '부산', '마산'],
    '할인 전 가격': [5000, 3000, 2500]
    })

df

     상품  지역  할인 전 가격
0  특산품A  안산     5000
1  특산품B  부산     3000
2  특산품C  마산     2500

In [19]:
#apply() -> 각 시리즈(컬럼별) 값에 함수 적용

df['할인 후 가격'] = df['할인 전 가격'].apply(lambda x: x*0.8).astype(np.int64)

df

     상품  지역  할인 전 가격  할인 후 가격
0  특산품A  안산     5000     4000
1  특산품B  부산     3000     2400
2  특산품C  마산     2500     2000

In [20]:
#filter()

list(filter(lambda x: (x > 2500), df['할인 후 가격']))

[4000]

In [21]:
#map()

df['할인 후 가격_map'] = df['할인 전 가격'].map(lambda x: x*0.8)

df

     상품  지역  할인 전 가격  할인 후 가격  할인 후 가격_map
0  특산품A  안산     5000     4000       4000.0
1  특산품B  부산     3000     2400       2400.0
2  특산품C  마산     2500     2000       2000.0

In [22]:
#조건에 따른 map()

df['할인 후 가격_map_조건'] = df['할인 전 가격'].map(lambda x: '추천' if x < 2600 else '비추천')

df

     상품  지역  할인 전 가격  할인 후 가격  할인 후 가격_map 할인 후 가격_map_조건
0  특산품A  안산     5000     4000       4000.0            비추천
1  특산품B  부산     3000     2400       2400.0            비추천
2  특산품C  마산     2500     2000       2000.0             추천

In [23]:
#오류 발생하는 경우 (1) - 데이터 프레임 전체 칼럼에 일괄적 함수 적용은 조심 #텍스트 데이터와 숫자 데이터 혼재

df.apply(lambda x: round(x, 1))

TypeError: ignored

In [24]:
#오류 발생하는 경우 (2) - Pandas 함수가 직접 존재하는 경우

df['할인 전 가격'].apply(lambda x: x.max()) #오류

AttributeError: ignored

In [25]:
df['할인 전 가격'].max() #정상

5000